controllers:
    resource: ../../src/Controller/
    type: annotation

adminController:
    resource: ../../src/Controller/Admin
    type: annotation
    prefix: /admin

kernel:
    resource: ../../src/Kernel.php
    type: annotation
